# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publisehd_date',
            new_name='published_date',
        ),
    ]
